### ISSUE TITLE
Картинка логотипа лежит вне блока, к которому она относится

### ISSUE THREAD

**Issue by igosheva** [TumanovV/Loftschool#1]
https://github.com/TumanovV/Loftschool/blob/1db283d02f7816922f886071c391de0a0342d6fc/index.html#L15

**Comment by TumanovV** [comment]
<div class="wrapper">
        <div class="header">
          <div class="container">
            <a href="#" class="logo">Ародита</a>  
            <div class="contacts">
              <div class="contacts__phone">8(800)00-392-10</div>
              <div class="contacts__desc">
                <a href="#" class="contacts__link">График работы</a>
              </div>
