### ISSUE TITLE
Добавить класс

### ISSUE THREAD

**Issue by igosheva** [TumanovV/Loftschool#10]
https://github.com/TumanovV/Loftschool/blob/1db283d02f7816922f886071c391de0a0342d6fc/index.html#L175

**Comment by igosheva** [comment]
голых тегов на странице быть не должно!

**Comment by TumanovV** [comment]
![2017-09-22_23-10-59](https://user-images.githubusercontent.com/31804972/30762628-60fb6240-9feb-11e7-987e-09d9e8d77815.png)
