### ISSUE TITLE
Нейминг не по БЭМ

### ISSUE THREAD

**Issue by igosheva** [TumanovV/Loftschool#2]
https://github.com/TumanovV/Loftschool/blob/1db283d02f7816922f886071c391de0a0342d6fc/index.html#L18

**Comment by igosheva** [comment]
У элемента contacts_phone и contacts_desc нейминг не по БЭМ.  Через одно "_" именуются классы с модификатором, а если ты хочешь назвать элемент, используй два нижних подчеркивания "__"

**Comment by TumanovV** [comment]
<div class="contacts__phone">8(800)00-392-10</div>
              <div class="contacts__desc">...
