### ISSUE TITLE
Телефон и "график работы" должны лежать на одном уровне вложенности, рядом, т.е. быть соседями. а не друг в друге.

### ISSUE THREAD

**Issue by igosheva** [TumanovV/Loftschool#3]
https://github.com/TumanovV/Loftschool/blob/1db283d02f7816922f886071c391de0a0342d6fc/index.html#L18

**Comment by TumanovV** [comment]
<div class="contacts">
              <div class="contacts__phone">8(800)00-392-10</div>
              <div class="contacts__desc">
                <a href="#" class="contacts__link">График работы</a>
              </div>
            </div>
