### ISSUE TITLE
Сделай этот элемент ссылкой, чтобы пользователь имел возможность позвонить с твоего сайта. И поставь href="tel:8(800)00-392-10"

### ISSUE THREAD

**Issue by igosheva** [TumanovV/Loftschool#4]
https://github.com/TumanovV/Loftschool/blob/1db283d02f7816922f886071c391de0a0342d6fc/index.html#L18

**Comment by TumanovV** [comment]
<a href="tel:+78000039210" class="contacts__phone">8 (800) 00-392-10</a>
