### ISSUE TITLE
В этом блоке должно лежать все содержимое контента страницы (т.е. все, что лежит в следующем теге container вместе с ним)

### ISSUE THREAD

**Issue by igosheva** [TumanovV/Loftschool#5]
https://github.com/TumanovV/Loftschool/blob/1db283d02f7816922f886071c391de0a0342d6fc/index.html#L27

**Comment by TumanovV** [comment]
div class="content">
          <div class="container">
              <div class="sidebar">
                  <ul class="nav">
                    <li class="nav__item">
                      <a href="" class="nav__link">
                        <img src="../img/nav1.jpg" alt="" class="nav__icon">
                        <div class="nav__text">Главная</div>
                      </a>
                    </li>
                    <li class="nav__item">
                        <a href="" class="nav__link">
                          <img src="../img/nav2.jpg" alt="" class="nav__icon">
                          <div class="nav__text">Услуги</div>
                        </a>
                      </li>
                      <li class="nav__item">
                          <a href="" class="nav_link">
                            <img src="../img/nav3.jpg" alt="" class="nav__icon">
                            <div class="nav__text">Отзывы</div>
                          </a>
                        </li>
                  </ul>
                </div>
            <div class="section">
              <ul class="breadcrumbs">
                <li class="breadcrumbs__item">
                  <a href="" class="breadcrumbs__link">Главная</a>
                </li>
                <li class="breadcrumbs__item">
                    <div class="text">Услуги</div>
                  </li>               
              </ul>
              <h1 class="title">
                Услуги
              </h1>
              <ul class="service">
                <li class="service__item">
                  <div class="service__avatar">
                    <img src="../img/1s.jpg" alt="" class="service__avatar-pic">
                  </div>
                  <div class="service__desc">
                    <div class="service__name">
                      Фитнес
                    </div>
                    <div class="service__content">
                      Фитнес-это основное направление в нашем центре.
                      Открыто 6 залов для занятий с 7-00 до 22-00.
                      Работают 24 фитнес-тренера, есть авторские и классические программы для
                      похудения, восстановления фигуры, здоровья и молодости. Занятия с персональным
                      тренером помогут достичь максимального результата в сжатые скроки.
                    </div>
                  </div>
                </li>
                <li class="service__item">
                  <div class="service__avatar">
                    <img src="../img/2s.jpg" alt="" class="service__avatar-pic">
                  </div>
                  <div class="service_desc">
                    <div class="service__name">
                      Личный диетолог
                    </div>
                    <div class="service__content">
                      Поможет вам получить более заметный результат от тренировок.
                      Создаст меню на каждый день, с учетом вкусовых предпочтений
                      и особенностей здоровья.
                      Проанализирует текуший рацион и укажет на ошибки. Поможет сделать питание
                      разнообразным и полезным, объяснит доступно о важной роли тех или иных витаминов
                      и микроэлементов.
                    </div>
                  </div>
                </li>
                <li class="service__item">
                  <div class="service__avatar">
                    <img src="../img/3s.jpg" alt="" class="service__avatar-pic">
                  </div>
                  <div class="service__desc">
                    <div class="service__name">
                      Йога
                    </div>
                    <div class="service__content">
                      Гармония души и тела - это базовая составляющая здоровья и красоты.
                      Наш зал для занятий йони открыт для людей всех возрастов без ограничений.
                      Отдельным направлением является йога для беременных с более щадящей программой.
                      Йога тренеры имеют сертификаты и являются победителями международных конкурсов.
                    </div>
                  </div>
                </li>
                <li class="service__item">
                  <div class="service__avatar">
                    <img src="../img/4s.jpg" alt="" class="service__avatar-pic">
                  </div>
                  <div class="service__desc">
                    <div class="service__name">
                      Петли TPX
                    </div>
                    <div class="service__content">
                      Новое направление для вашего центра, которое стало одним из самых популярных
                      и востребованных. Программа TPX Suspension Training создана для людей с начальным
                      уровнем подготовки и позволяет  эффективно тренироваться, используя нарастающую нагрузку,
                      которая зависит от силы и массы человека. Петли усиливают ловкость, гибкость и подвижность.
                      В нашем центре проводятся индивидуальные и групповые тренировки TPX.
                    </div>
                  </div>
                </li>
                <li class="service__item">
                  <div class="service__avatar">
                    <img src="../img/5s.jpg" alt="" class="service__avatar-pic">
                  </div>
                  <div class="service__desc">
                    <div class="service__name">
                      Кроссфит
                    </div>
                    <div class="service__content">
                      Авторская запатентованная программа тренировки, включающая элементы тяжелой атлетики,
                      занятий с гирями, гимнастики. Данная программа безупречно подходит для ежедневных тренировко людям
                      с сидячим образом жизни. Преимущество кроссфита в том, что он ожинаково хорошо воспринимается и мужчинами,
                      и женщинами и подходит для семейных групповых тренировок. Высокая эффективность программы обусловлена
                      чуткими рекомендациями наших сертефицированных тренеров.

                    </div>
                  </div>
                </li>
                <li class="service__item">
                  <div class="service__avatar">
                    <img src="../img/6s.jpg" alt="" class="service__avatar-pic">
                  </div>
                  <div class="service__desc">
                    <div class="service__name">
                      Басейн
                    </div>
                    <div class="service__content">
                      Большой 50 метровый бассейн, разделенный на 6 дорожек, позволит заниматься индивидуальным
                      плаванием или аквааэробикой. Занятия проводит сертифицированный тренер - Ситник Ирина Валерьевна,
                      известная своими успехами в школе подготовки олимпийского резерва. В бассейне есть место для
                      занятий с детьми (ежедневно с 12-00 дл 14-00), а так же провродится аквааэробика для беременных
                      каждый день в 10-00 и 19-00.
                    </div>
                  </div>
                </li>
              </ul>
            </div> 
          </div>
        </div>

**Comment by TumanovV** [comment]
Не знаю, как лучше скинуть, может скриншотами?

**Comment by TumanovV** [comment]
![2017-09-22_23-02-52](https://user-images.githubusercontent.com/31804972/30762304-3c245afe-9fea-11e7-94bb-bb007e493a71.png)
