### ISSUE TITLE
Ошибка в нейминге

### ISSUE THREAD

**Issue by igosheva** [TumanovV/Loftschool#7]
https://github.com/TumanovV/Loftschool/blob/1db283d02f7816922f886071c391de0a0342d6fc/index.html#L151

**Comment by igosheva** [comment]
Через одно "_" именуются классы с модификатором, а если ты хочешь назвать элемент, используй два нижних подчеркивания "__"

**Comment by igosheva** [comment]
service_avatar - тоже самое

**Comment by igosheva** [comment]
footer_text - тоже самое

**Comment by TumanovV** [comment]
![2017-09-22_23-05-01](https://user-images.githubusercontent.com/31804972/30762420-a9108bc4-9fea-11e7-90de-583a376ffcc8.png)
![2017-09-22_23-05-26](https://user-images.githubusercontent.com/31804972/30762417-a9031386-9fea-11e7-8354-9a37d9f04cde.png)
![2017-09-22_23-05-54](https://user-images.githubusercontent.com/31804972/30762418-a90353a0-9fea-11e7-8e94-1e747e7cf000.png)
