### ISSUE TITLE
Лишний элемент

### ISSUE THREAD

**Issue by igosheva** [TumanovV/Loftschool#8]
https://github.com/TumanovV/Loftschool/blob/1db283d02f7816922f886071c391de0a0342d6fc/index.html#L34

**Comment by igosheva** [comment]
Этот элемент можно будет потом сделать как псевдоэлемент к последнему breadcrumbs__item. Пока можешь просто перед текстом последнего элемента добавить этот слеш

**Comment by TumanovV** [comment]
![2017-09-22_23-07-53](https://user-images.githubusercontent.com/31804972/30762515-ea854f68-9fea-11e7-982d-d1a731cf8e24.png)

Пока так, сейчас буду через "хлебные крошки делать"
