### ISSUE TITLE
Все последующие элементы должны лежать внутри футера и оборачиваться блоком с классом container

### ISSUE THREAD

**Issue by igosheva** [TumanovV/Loftschool#9]
https://github.com/TumanovV/Loftschool/blob/1db283d02f7816922f886071c391de0a0342d6fc/index.html#L171

**Comment by TumanovV** [comment]
![2017-09-22_23-09-04](https://user-images.githubusercontent.com/31804972/30762570-14cd89d4-9feb-11e7-8156-7aa5f8f38013.png)
